config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  get "/lists", to: "lists#index", as: "lists"
  get "/lists/new",to: "lists#new", as: "new_list"
  get "/lists/:id", to: "lists#show", as: "list"
  post "lists",to:"lists#create"
  delete "lists/:id",to:"lists#destroy",as: "delete_list"
  get "/lists/:list_id/bookmarks/new",to:"bookmarks#new",as:"new_bookmark"
  post "/lists/:list_id/bookmarks",to:"bookmarks#create",as:"create_bookmark"
  delete "bookmarks/:id",to:"bookmarks#destroy",as:"delete_bookmark"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment,length: {minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:list_id]

end

app/models/list.rb
class List < ApplicationRecord
  validates :name,presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title,presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy!
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end


  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show,:destroy]

  def index
    @count = List.count
    @lists = List.all
  end


  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path,status: :see_other
  end


  private
  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="form-container">
<%= simple_form_for([@list,@bookmark],url:create_bookmark_path(@list)) do |f|%>
  <%= f.input :comment, placeholder: "Enter a comment about the movie"%>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgainList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |i|%>
  <%= i.input :name%>

  <%= i.submit%>
<% end %>

app/views/lists/index.html.erb
<body>

<span class="main-title">MovieTime</span>

<div class="new-list-link">
  <% if @count == 0 %>
    <%= link_to " 👉 Create a new list 👈", new_list_path,class:"add-button" %>
  <% else %>
    <%= link_to "👉 Add another list 👈", new_list_path,class:"add-button"%>
  <% end %>
</div>
p
<%# LISTS  %>
<% @lists.each do |list| %>
  <div class="list-container">
    <%= link_to list.name, list_path(list),class:"list-item" %>
  </div>
<% end %>

</body>

app/views/lists/new.html.erb
<div class="form-container">
<%= render 'form', list:@list%>
</div>

app/views/lists/show.html.erb
<div class="list-name">
  <strong><%= @list.name %></strong>
</div>

<div class="empty-message">
  <% if @list.bookmarks.count.zero? %>
    <%= link_to "List has no Bookmarks yet...Click here to add", new_bookmark_path(@list), class: "no-decoration-link" %>
  <% end %>
</div>

<div class="main-container">
  <% @list.movies.each do |movie| %>
    <div class="bookmark-card" data-controller="movie-modal" data-movie-id="<%= movie.id %>">
      <div class="bookmark-image">
        <%= image_tag movie.poster_url %>
      </div>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="bookmark-movie"><%= movie.title %></div>
      <div class="bookmark-comment"><%= "'#{bookmark.comment}'" %></div>
      <%= link_to delete_bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this bookmark?" }, class: "text-danger" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  <% end %>
</div>

<footer>
  <%= render 'shared/footer' %>
</footer>

app/views/modals/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  <!-- Modal content goes here -->
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/shared/_footer.html.erb
<div class="t-footer">

  <%= link_to root_path do %>
  <i class="fa-solid fa-house"></i>
  <% end %>

  <%= link_to new_bookmark_path(@list) do %>
    <i class="fas fa-bookmark"></i>
  <% end %>


  <%= link_to delete_list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" }, class: "text-danger" do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>

</div>